
/****** Object:  Database [AnswerProjectBoard]    Script Date: 09/12/2013 16:21:20 ******/
CREATE DATABASE [AnswerProjectBoard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AnswerProjectBoard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AnswerProjectBoard.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AnswerProjectBoard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AnswerProjectBoard_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AnswerProjectBoard] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AnswerProjectBoard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AnswerProjectBoard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET ARITHABORT OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AnswerProjectBoard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AnswerProjectBoard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AnswerProjectBoard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AnswerProjectBoard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AnswerProjectBoard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET RECOVERY FULL 
GO

ALTER DATABASE [AnswerProjectBoard] SET  MULTI_USER 
GO

ALTER DATABASE [AnswerProjectBoard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AnswerProjectBoard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AnswerProjectBoard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AnswerProjectBoard] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AnswerProjectBoard] SET  READ_WRITE 
GO
